const _ = require("lodash")
// console.log(_.chunk([1,2,3,5],3))
// var name = "hello"
// if(_.isString(name))
//     {
//         console.log("is a string")
//     }

// console.log(_.compact([0, 1, false, 2, '', 3]))
// console.log(_.concat([12,2], 2, [3], [[4]]))
// console.log(_.difference([2, 1,44], [2, 3]))
// console.log(_.differenceBy([0.1, 1.4, 1.1], [3.3,2.3, 1.1]))
// console.log(_.differenceBy([{ 'x': 2 }, { 'x': 1 }], [{ 'x': 1 }], 'x'))
// var objects = [{ 'x': 1, 'y': 2 }, { 'x': 2, 'y': 1 }];
// console.log(_.differenceWith(objects, [{ 'x': 1, 'y': 2 }], _.isEqual))
var arr =[1, 2, 3]
arr = _.dropRightWhile(arr,[1,2])
// arr = _.dropRight(arr)
console.log(arr)
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()
// console.log()



// var Promise = require('bluebird');

// var mongoClient = Promise.promisifyAll(require('mongodb')).MongoClient;

// var url = 'mongodb://localhost/EmployeeDB';

// mongoClient.connectAsync(url,{ useUnifiedTopology: true })
// .then((db)=>db.collection('Employee').findAsync({}))
// .then((cursor) =>cursor.each((err, doc)=> console.log(doc)))
    